import type {
  Booking,
  BookingStatus,
  CreatedVia,
  Farmer,
  MandiCenter,
  Slot,
  StatusLogEntry,
} from "@/lib/types"
import { STAGE_ORDER } from "@/lib/status"
import { todayISO } from "@/lib/format"

/**
 * Deterministic in-memory stand-in for Supabase, used until P1/P6 hand over
 * credentials. Shapes match agriq_schema.sql exactly so swapping to the live
 * repository is a change of data source, not a change of component code.
 */

// Seeded PRNG so a reload shows the same desk — a demo that reshuffles every
// refresh is impossible to rehearse against.
function makeRng(seed: number) {
  let s = seed >>> 0
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0
    return s / 0x100000000
  }
}

const rng = makeRng(26032)
const pick = <T,>(arr: readonly T[]): T => arr[Math.floor(rng() * arr.length)]
const between = (lo: number, hi: number) => lo + rng() * (hi - lo)

function uuid(prefix: string, n: number): string {
  const hex = (n + 1).toString(16).padStart(12, "0")
  return `${prefix}0000-0000-4000-8000-${hex}`
}

const FIRST_NAMES = [
  "Manjunath", "Lakshmamma", "Basavaraj", "Gangamma", "Nagaraj", "Parvathamma",
  "Shivakumar", "Sharadamma", "Mallikarjun", "Kempamma", "Siddappa", "Renukamma",
  "Chandrashekar", "Yashodha", "Yallappa", "Savitri", "Veerabhadra", "Gowramma",
  "Ningappa", "Rathnamma", "Prakash", "Bhagyamma", "Shankarappa", "Nagarathna",
  "Ravikumar", "Sumitra", "Hanumantha", "Jayamma", "Girish", "Padmavathi",
]
const LAST_NAMES = [
  "Gowda", "Patil", "Hegde", "Shetty", "Reddy", "Naik", "Hiremath", "Desai",
  "Kulkarni", "Bhat", "Angadi", "Kamath", "Poojary", "Nayak",
]
const VILLAGES = [
  "Yelahanka", "Anekal", "Nelamangala", "Navalgund", "Kalghatgi", "Nanjangud",
  "T. Narsipur", "Aland", "Jewargi", "Bailhongal", "Saundatti", "Manvi",
  "Sindhanur", "Devadurga", "Hukkeri", "Kunigal",
]

/**
 * The same six APMC yards P2's farmer app and P4's USSD simulator use, with
 * their centre ids copied exactly. That is deliberate: a QR pass generated by
 * P2 in demo mode carries `center_id` c0000000-…, and matching ids here means
 * the whole system can be demonstrated end to end with no backend at all.
 */
export const MOCK_CENTERS: MandiCenter[] = [
  {
    center_id: "c0000000-0000-0000-0000-000000000001",
    center_name: "Bengaluru APMC (Yeshwanthpur Main Yard)",
    location: "Yeshwanthpur",
    district: "Bengaluru Urban",
    state: "Karnataka",
    crop_type: "Ragi",
    daily_capacity_kg: 60000,
    hourly_intake_limit: 45,
    avg_processing_min: 12,
    operating_start: "08:00:00",
    operating_end: "18:00:00",
    created_at: new Date().toISOString(),
  },
  {
    center_id: "c0000000-0000-0000-0000-000000000002",
    center_name: "Hubballi APMC (Amaragol Market Yard)",
    location: "Amaragol",
    district: "Dharwad",
    state: "Karnataka",
    crop_type: "Onion",
    daily_capacity_kg: 75000,
    hourly_intake_limit: 50,
    avg_processing_min: 14,
    operating_start: "08:00:00",
    operating_end: "18:00:00",
    created_at: new Date().toISOString(),
  },
  {
    center_id: "c0000000-0000-0000-0000-000000000003",
    center_name: "Mysuru APMC (Bandipalya Yard)",
    location: "Bandipalya",
    district: "Mysuru",
    state: "Karnataka",
    crop_type: "Paddy",
    daily_capacity_kg: 55000,
    hourly_intake_limit: 40,
    avg_processing_min: 15,
    operating_start: "08:00:00",
    operating_end: "18:00:00",
    created_at: new Date().toISOString(),
  },
  {
    center_id: "c0000000-0000-0000-0000-000000000004",
    center_name: "Kalaburagi APMC (Nehru Gunj Hub)",
    location: "Nehru Gunj",
    district: "Kalaburagi",
    state: "Karnataka",
    crop_type: "Tur",
    daily_capacity_kg: 80000,
    hourly_intake_limit: 60,
    avg_processing_min: 16,
    operating_start: "08:00:00",
    operating_end: "18:00:00",
    created_at: new Date().toISOString(),
  },
  {
    center_id: "c0000000-0000-0000-0000-000000000005",
    center_name: "Belagavi APMC Central Yard",
    location: "Belagavi",
    district: "Belagavi",
    state: "Karnataka",
    crop_type: "Maize",
    daily_capacity_kg: 50000,
    hourly_intake_limit: 35,
    avg_processing_min: 15,
    operating_start: "08:00:00",
    operating_end: "18:00:00",
    created_at: new Date().toISOString(),
  },
  {
    center_id: "c0000000-0000-0000-0000-000000000006",
    center_name: "Raichur Cotton & Paddy APMC",
    location: "Raichur",
    district: "Raichur",
    state: "Karnataka",
    crop_type: "Cotton",
    daily_capacity_kg: 70000,
    hourly_intake_limit: 50,
    avg_processing_min: 18,
    operating_start: "08:00:00",
    operating_end: "18:00:00",
    created_at: new Date().toISOString(),
  },
]


const TOKEN_PREFIX: Record<string, string> = {
  [MOCK_CENTERS[0].center_id]: "BLR",
  [MOCK_CENTERS[1].center_id]: "HBL",
  [MOCK_CENTERS[2].center_id]: "MYS",
  [MOCK_CENTERS[3].center_id]: "KLB",
  [MOCK_CENTERS[4].center_id]: "BGM",
  [MOCK_CENTERS[5].center_id]: "RCR",
}

/** Distribution of statuses across a mandi mid-morning. Weighted, not uniform. */
const STATUS_MIX: BookingStatus[] = [
  ...Array<BookingStatus>(9).fill("BOOKED"),
  ...Array<BookingStatus>(5).fill("CHECKED_IN"),
  ...Array<BookingStatus>(4).fill("WEIGHED"),
  ...Array<BookingStatus>(3).fill("QUALITY_APPROVED"),
  ...Array<BookingStatus>(2).fill("PAYMENT_INITIATED"),
  ...Array<BookingStatus>(7).fill("COMPLETED"),
  "NO_SHOW",
  "CANCELLED",
]

function buildSlots(center: MandiCenter, date: string, startIdx: number): Slot[] {
  const startHour = Number((center.operating_start ?? "08:00:00").slice(0, 2))
  const endHour = Number((center.operating_end ?? "18:00:00").slice(0, 2))
  const slots: Slot[] = []
  for (let h = startHour, i = 0; h < endHour; h++, i++) {
    slots.push({
      slot_id: uuid("50700000", startIdx + i),
      center_id: center.center_id,
      slot_date: date,
      slot_start_time: `${String(h).padStart(2, "0")}:00:00`,
      slot_end_time: `${String(h + 1).padStart(2, "0")}:00:00`,
      max_farmers: center.hourly_intake_limit ?? 10,
      booked_count: 0,
    })
  }
  return slots
}

export interface MockDb {
  farmers: Farmer[]
  centers: MandiCenter[]
  slots: Slot[]
  bookings: Booking[]
  status_log: StatusLogEntry[]
}

function seed(): MockDb {
  const today = todayISO()
  const farmers: Farmer[] = []
  const slots: Slot[] = []
  const bookings: Booking[] = []
  const status_log: StatusLogEntry[] = []

  let slotCursor = 0
  for (const center of MOCK_CENTERS) {
    const centerSlots = buildSlots(center, today, slotCursor)
    slotCursor += centerSlots.length
    slots.push(...centerSlots)
  }

  let farmerIdx = 0
  let bookingIdx = 0
  let logIdx = 0
  const dayStart = new Date()
  dayStart.setHours(8, 0, 0, 0)

  for (const center of MOCK_CENTERS) {
    const centerSlots = slots.filter((s) => s.center_id === center.center_id)
    // Busiest center gets the fullest desk so the demo has something to show.
    const count = center.center_id === MOCK_CENTERS[0].center_id ? 34 : Math.round(between(9, 18))

    for (let i = 0; i < count; i++) {
      const farmer: Farmer = {
        farmer_id: uuid("fa120000", farmerIdx),
        full_name: `${pick(FIRST_NAMES)} ${pick(LAST_NAMES)}`,
        phone_number: `9${Math.floor(between(100000000, 999999999))}`,
        village: pick(VILLAGES),
        district: center.district,
        state: center.state,
        preferred_lang: rng() > 0.65 ? "kn" : "en",
        created_at: new Date(dayStart.getTime() - 86400000 * 30).toISOString(),
      }
      farmers.push(farmer)
      farmerIdx++

      const slot = centerSlots[Math.min(centerSlots.length - 1, Math.floor(rng() * centerSlots.length))]
      slot.booked_count++

      const status = pick(STATUS_MIX)
      const idx = STAGE_ORDER.indexOf(status)
      const createdVia: CreatedVia = rng() > 0.72 ? "ussd" : "web"

      // Timestamps walk backwards from now so elapsed-time columns look real.
      const checkedInAt =
        idx >= 1 ? new Date(dayStart.getTime() + between(0, 3.5) * 3600000).toISOString() : null
      const completedAt =
        status === "COMPLETED" && checkedInAt
          ? new Date(new Date(checkedInAt).getTime() + between(28, 95) * 60000).toISOString()
          : null

      const weight = idx >= 2 ? Math.round(between(400, 3200) / 10) * 10 : null
      const grade = idx >= 3 ? pick(["FAQ", "A", "A", "B", "B", "C"]) : null
      const amount = idx >= 4 && weight ? Math.round((weight * between(18, 34)) / 10) * 10 : null

      const booking: Booking = {
        booking_id: uuid("b0000000", bookingIdx),
        farmer_id: farmer.farmer_id,
        slot_id: slot.slot_id,
        center_id: center.center_id,
        token_number: `${TOKEN_PREFIX[center.center_id]}-${String(1001 + i).padStart(4, "0")}`,
        crop_quantity_kg: weight,
        quality_grade: grade,
        payment_amount: amount,
        status,
        queue_position: i + 1,
        predicted_wait_mins: Math.round(between(15, 120)),
        actual_wait_mins: completedAt
          ? Math.round((new Date(completedAt).getTime() - new Date(checkedInAt!).getTime()) / 60000)
          : null,
        created_via: createdVia,
        checked_in_at: checkedInAt,
        completed_at: completedAt,
        created_at: new Date(dayStart.getTime() - between(1, 96) * 3600000).toISOString(),
      }
      bookings.push(booking)
      bookingIdx++

      // Replay the transitions this booking must have gone through, so the
      // bottleneck panel has real dwell times to chew on.
      let prev: BookingStatus = "BOOKED"
      let t = checkedInAt ? new Date(checkedInAt).getTime() : new Date(booking.created_at).getTime()
      const walked = idx > 0 ? STAGE_ORDER.slice(1, idx + 1) : []
      for (const to of walked) {
        status_log.push({
          log_id: uuid("10600000", logIdx++),
          booking_id: booking.booking_id,
          from_status: prev,
          to_status: to,
          changed_by: pick(["officer.gowda", "officer.hiremath", "officer.shetty"]),
          created_at: new Date(t).toISOString(),
        })
        prev = to
        t += between(8, 34) * 60000
      }
      if (status === "CANCELLED" || status === "NO_SHOW") {
        status_log.push({
          log_id: uuid("10600000", logIdx++),
          booking_id: booking.booking_id,
          from_status: "BOOKED",
          to_status: status,
          changed_by: "officer.rane",
          created_at: new Date(dayStart.getTime() + between(1, 4) * 3600000).toISOString(),
        })
      }
    }
  }

  // P2's demo pass, seeded verbatim so the two apps can be shown together with
  // no backend: their farmer app renders this exact QR in demo mode, and
  // scanning it here resolves to a real row instead of "not on today's list".
  // Ids come from farmer-app/src/lib/mockData.ts on P2's branch.
  const p2Centre = MOCK_CENTERS[0]
  const p2Slot = slots.find((sl) => sl.center_id === p2Centre.center_id)!
  const p2Farmer: Farmer = {
    farmer_id: "f1111111-1111-1111-1111-111111111111",
    full_name: "Manjunath Gowda",
    phone_number: "9845012345",
    village: "Yelahanka",
    district: p2Centre.district,
    state: p2Centre.state,
    preferred_lang: "kn",
    created_at: new Date(dayStart.getTime() - 86400000 * 12).toISOString(),
  }
  farmers.push(p2Farmer)
  p2Slot.booked_count++
  bookings.push({
    booking_id: "b1111111-1111-1111-1111-111111111101",
    farmer_id: p2Farmer.farmer_id,
    slot_id: p2Slot.slot_id,
    center_id: p2Centre.center_id,
    token_number: "BLR-0231",
    crop_quantity_kg: null,
    quality_grade: null,
    payment_amount: null,
    status: "BOOKED",
    queue_position: 1,
    predicted_wait_mins: 25,
    actual_wait_mins: null,
    created_via: "web",
    checked_in_at: null,
    completed_at: null,
    created_at: new Date(dayStart.getTime() - 3600000 * 5).toISOString(),
  })

  return { farmers, centers: [...MOCK_CENTERS], slots, bookings, status_log }
}

export const mockDb: MockDb = seed()
